
// This file has been generated by the GUI designer. Do not modify.
namespace VotingMultiChain
{
	public partial class VotingWindow
	{
		private global::Gtk.VBox vbox4;

		private global::Gtk.Label votingTitle;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Button getAddressButton;

		private global::Gtk.Entry newAddressEntry;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget VotingMultiChain.VotingWindow
			this.Name = "VotingMultiChain.VotingWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("VotingWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.BorderWidth = ((uint)(10));
			// Container child VotingMultiChain.VotingWindow.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.votingTitle = new global::Gtk.Label();
			this.votingTitle.Name = "votingTitle";
			this.votingTitle.LabelProp = global::Mono.Unix.Catalog.GetString("Voting Station");
			this.vbox4.Add(this.votingTitle);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.votingTitle]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.getAddressButton = new global::Gtk.Button();
			this.getAddressButton.CanFocus = true;
			this.getAddressButton.Name = "getAddressButton";
			this.getAddressButton.UseUnderline = true;
			this.getAddressButton.Label = global::Mono.Unix.Catalog.GetString("Get new Address");
			this.hbox7.Add(this.getAddressButton);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.getAddressButton]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.newAddressEntry = new global::Gtk.Entry();
			this.newAddressEntry.CanFocus = true;
			this.newAddressEntry.Name = "newAddressEntry";
			this.newAddressEntry.IsEditable = true;
			this.newAddressEntry.InvisibleChar = '•';
			this.hbox7.Add(this.newAddressEntry);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.newAddressEntry]));
			w3.Position = 1;
			this.vbox4.Add(this.hbox7);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox7]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.Add(this.vbox4);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
			this.getAddressButton.Clicked += new global::System.EventHandler(this.OnGetAddressButtonClicked);
		}
	}
}
